export { GitHubIcon } from './GitHubIcon';
export { TelegramIcon } from './TelegramIcon';
export { TwitterIcon } from './TwitterIcon';
export { TwitterIcon2 } from './TwitterIcon2';
export { ArrowRightIcon } from './ArrowRightIcon';
export { CopyClipboardIcon } from './CopyClipboardIcon';
export { DiscordIcon } from './DiscordIcon';
export { DownloadIcon } from './DownloadIcon';
export { SpinnerIcon } from './SpinnerIcon';
export { ChevronDownIcon } from './ChevronDownIcon';
export { CloseIcon } from './CloseIcon';
export { DoneIcon } from './DoneIcon';
export { WarningIcon } from './WarningIcon';
export { SolfareIcon, SolletIcon, PhantomIcon } from './WalletIcons';
export { ArrowDownSmallIcon } from './arrowDownSmall';
export { ArrowLeftIcon } from './ArrowLeftIcon';
export { CountdownIcon } from './CountdownIcon';
export { FinishFlagsIcon } from './FinishFlagsIcon';
