export const PATHS = {
  ROOT: '/',
  WALLET: '/wallet',
  PROFILE: '/profile',
  PAGE_404: '/404',
  WALLET_PUBKEY: '/:walletPubkey',
  BORROW_ROOT: '/borrow',
  BORROW_BULK_SUGGESTION: '/borrow/bulk-suggestion',
  BORROW_BULK_OVERVIEW: '/borrow/bulk-overview',
  BORROW_MANUAL: '/borrow/manual',
  BORROW_LITE: '/borrow/lite',
  BORROW_SUCCESS: '/borrow/success',
  ADVENTURES: '/adventures',
  LEND: '/lend',
  STRATEGIES: '/strategies',
  MY_STRATEGIES: '/my-strategies',
  STRATEGY_CREATION: '/my-strategies/create',
  LIQUIDATIONS: '/liquidations',
  BONDS: '/bonds',
  BONDS_LITE: '/bonds-lite',
  BOND: '/bond',
  LOANS: '/loans',
  OFFER: '/offer',
  ROADMAP: 'https://trello.com/b/jt9JRdLg/frakt-public-roadmap',
};
