export const PATHS = {
  ROOT: '/',
  WALLET: '/wallet',
  PROFILE: '/profile',
  PAGE_404: '/404',
  WALLET_PUBKEY: '/:walletPubkey',
  BORROW: '/borrow-old',
  BORROW_ROOT: '/borrow',
  BORROW_BULK_SUGGESTION: '/borrow/bulk-suggestion',
  BORROW_BULK_CHECKOUT: '/borrow/bulk-checkout',
  BORROW_MANUAL: '/borrow/manual',
  LEND: '/lend',
  LIQUIDATIONS: '/liquidations',
  BONDS: '/bonds',
  BOND: '/bond',
  LOANS: '/loans',
  POOLS_CREATION: '/bond/:marketPubkey/create',
  ROADMAP: 'https://trello.com/b/jt9JRdLg/frakt-public-roadmap',
};
