export const PATHS = {
  ROOT: '/',
  WALLET: '/wallet',
  PROFILE: '/profile',
  PAGE_404: '/404',
  WALLET_PUBKEY: '/:walletPubkey',
  BORROW: '/borrow',
  LEND: '/lend',
  LIQUIDATIONS: '/liquidations',
  BOND: '/bond',
  LOANS: '/loans',
  BONDS: '/bonds',
  POOLS_CREATION: '/poolscreation',
  ROADMAP: 'https://trello.com/b/jt9JRdLg/frakt-public-roadmap',
};
