export const URLS = {
  ROOT: '/',
  SWAP: '/swap',
  MARKET: '/market',
  MARKET_BUY: '/market/buy',
  MARKET_SELL: '/market/sell',
  MARKET_SWAP: '/market/swap',
  MARKET_INFO: '/market/info',
  VAULTS: '/vaults',
  VAULT: '/vault',
  STAKER_PAGE: '/staker',
  FRAKTIONALIZE: '/fraktionalize',
  WALLET: '/wallet',
  PAGE_404: '/404',
  COLLECTIONS: '/collections',
  COLLECTION: '/collection',
  DEX: 'https://dex.fraktion.art',
};
