export const VAULTS_AND_META_CACHE_URL = process.env.REACT_APP_CACHE_URL;

export const ADDITIONAL_VERIFIED_VAULTS = [
  'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
  '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
];
