import BN from 'bn.js';
import { VaultData, VaultState } from '../../../../../../contexts/fraktion';

export const SLIDER_DATA: VaultData[] = [
  {
    allowFurtherShareCreation: false,
    auction: {
      auction: {
        tickSize: new BN(1),
        auctionPubkey: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
        currentWinningBidPubkey: '11111111111111111111111111111111',
        endingAt: null,
        isEnabled: true,
        isStarted: false,
        startedAt: null,
        vaultPubKey: '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
      },
      bids: [],
    },
    authority: 'CYoxVCf8HoXEF6suec1XQT318DVcb79155XjAma1EeJ9',
    createdAt: 1644978442,
    fractionMint: '2pqRgpTLSJRgqBaBAQBBAqfLsdjqWic5bi6S9UJazyaT',
    fractionTreasury: 'HKrKdyE6tUYfAEGMRMMbwisveSX8sZzHKH7p7DkqbJh8',
    fractionsSupply: new BN(1),
    hasMarket: true,
    isVerified: true,
    key: 3,
    lockedPricePerShare: new BN(1),
    priceMint: 'So11111111111111111111111111111111111111112',
    pricingLookupAddress: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
    realState: VaultState.Active,
    redeemTreasury: '3nX9fFj9P3A4saKviyfBX8prRXvcPySj4aYATmUG6Gyv',
    safetyBoxes: [
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: '',
        nftDescription: '',
        nftImage:
          'https://arweave.net/QTbFKiBGSYIJJna0QafYgAxNyAtuhwssEJliiJa0eyE?ext=png',
        nftMint: 'DQVXUS56q8PxeTd3VcmRT39mmVyZi5qmsywYKwCP64VU',
        nftName: 'The Fearless',
        order: 0,
        safetyBoxPubkey: '5UeQiPNTuctci2yXkVpC1mmft6oaPHbf9gNFmKdc72s1',
        store: '9JXKZ1f36MJxTYjQVexqPv1s5rCKbGaVt4UsTjhZ2smu',
        vaultPubkey: '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
      },
    ],
    state: 1,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    tokenTypeCount: 1,
    vaultPubkey: '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
  },
  {
    allowFurtherShareCreation: false,
    auction: {
      auction: {
        tickSize: new BN(1),
        auctionPubkey: 'Fr5MQcK98U8zQoD3yuomHsyx1hv3T1371jPnJbrNgPWr',
        currentWinningBidPubkey: '11111111111111111111111111111111',
        endingAt: null,
        isEnabled: true,
        isStarted: false,
        startedAt: null,
        vaultPubKey: 'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
      },
      bids: [],
    },
    authority: 'GbwgZkQLvSGt1beu1gv3g62Tdw1PXo9eXP6d14PDW1HB',
    createdAt: 1643827898,
    fractionMint: '2pqRgpTLSJRgqBaBAQBBAqfLsdjqWic5bi6S9UJazyaT',
    fractionTreasury: 'HKrKdyE6tUYfAEGMRMMbwisveSX8sZzHKH7p7DkqbJh8',
    fractionsSupply: new BN(1),
    hasMarket: true,
    isVerified: true,
    key: 3,
    lockedPricePerShare: new BN(1),
    priceMint: 'So11111111111111111111111111111111111111112',
    pricingLookupAddress: 'Fr5MQcK98U8zQoD3yuomHsyx1hv3T1371jPnJbrNgPWr',
    realState: VaultState.Active,
    redeemTreasury: 'VizAA22NLKm4qbGCa5ho5xmv87BLzVKn7EdhVbzWnGV',
    safetyBoxes: [
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'MonkeBack',
        nftDescription: '',
        nftImage:
          'https://www.arweave.net/5GH2R2gj_iBns1PsRfvEqIFI7GLL_-8Kf2BTEAdfdmU?ext=png',
        nftMint: 'CRG8ZbuKL4tfjeQEixZPKfG9AVbHR2oeKymyLesJFkK',
        nftName: 'monkeBack #4834',
        order: 765,
        safetyBoxPubkey: 'J4gsf1R3AwmMd4MX6yZC8UPDekydQa1TvseGQDCesxaK',
        store: '9pJekgCBw4HvAXRoxFsgUDpMq6PsbvRqXN7nebsSMq7F',
        vaultPubkey: 'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
      },
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'MonkeBack',
        nftDescription: '',
        nftImage:
          'https://www.arweave.net/PQ7y9RdRXwbGvfTfj1ZewLwOwT1UD2pEvQa_dPSU_dI?ext=png',
        nftMint: 'EKDteuVF8A7ipG3BrpJyceAfnHvPkQJRsaBw8ad1sKVm',
        nftName: 'monkeBack #4625',
        order: 764,
        safetyBoxPubkey: 'GV2jUSg6VNqSdP6GwK6MRyjSTtdSQSpUcMfRtJNZXSfi',
        store: '27gcSvCJ4KVMcnPSU9iRphnNq1cF29dNEKtShBAuNNbX',
        vaultPubkey: 'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
      },
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'MonkeBack',
        nftDescription: '',
        nftImage:
          'https://www.arweave.net/czWn3MyDulHzxIJej0-bwNlsiu_LahH4rDhNzegVe1k?ext=png',
        nftMint: 'HVKawXmbqS2HP9Pis2AuzYXYAnVRbX2fCqSKoLx2i7hk',
        nftName: 'monkeBack #4424',
        order: 763,
        safetyBoxPubkey: '22FVkVfjVg6cgLiyvuqsGgECwe6YdwadijN3BHPwdVqu',
        store: '7ZaA9aGDLvbZdBXbcmu7ANM4GvjeioMmcbDK1sEdoLs3',
        vaultPubkey: 'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
      },
    ],
    state: 1,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    tokenTypeCount: 766,
    vaultPubkey: 'DLRCcdmBJvoR6nHTpKRKvRBE9n8TN1443rN3VrtiXzqp',
  },
  {
    allowFurtherShareCreation: false,
    auction: {
      auction: {
        tickSize: new BN(1),
        auctionPubkey: '9HrD33d5rdYKk6pSAANT4fqot8jadzi3mMaRfryb3e1T',
        currentWinningBidPubkey: '11111111111111111111111111111111',
        endingAt: null,
        isEnabled: true,
        isStarted: false,
        startedAt: null,
        vaultPubKey: 'Uzp4nRWuZozb36PbjepYJGM5Q44Bqiw1nYrDfQC1Hd1',
      },
      bids: [],
    },
    authority: '3wNuhLHe3TmE8PnhCes7XbMFryfSDZbZgw8hc9kDTfzF',
    createdAt: 1642342174,
    fractionMint: 'FUNHP94B46a486h5RSv46aeWUkeM5goTUuM5mVh4L6Qr',
    fractionTreasury: 'CdjVgzon7TtRnwHTLfQAdRZfw7bSFoGnW9YihLirkeen',
    fractionsSupply: new BN(1),
    hasMarket: true,
    isVerified: true,
    key: 3,
    lockedPricePerShare: new BN(1),
    priceMint: 'So11111111111111111111111111111111111111112',
    pricingLookupAddress: '9HrD33d5rdYKk6pSAANT4fqot8jadzi3mMaRfryb3e1T',
    realState: VaultState.Active,
    redeemTreasury: 'VizAA22NLKm4qbGCa5ho5xmv87BLzVKn7EdhVbzWnGV',
    safetyBoxes: [
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'Boryoku Babyz',
        nftDescription: '',
        nftImage:
          'https://arweave.net/dRSeuO3frNtYk50t3JPJtO0ySLJJP5ukFOuVHiYske4?ext=png',
        nftMint: 'FdwtAhXTWYNU5NyuKMrCMg7eswxjYUsV38W84nsVLQ94',
        nftName: 'Boryoku Babyz #227',
        order: 12,
        safetyBoxPubkey: 'BZhso7kziz3fC2m8GWZZg8SfHMfSjMZjjnxVFAMg5RTR',
        store: '8pc8DdiCHzWYtVXgtBg1rjnUPFY7CupMCYxv2mAnMS5P',
        vaultPubkey: 'Uzp4nRWuZozb36PbjepYJGM5Q44Bqiw1nYrDfQC1Hd1',
      },
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'Lifinity Protocol',
        nftDescription: '',
        nftImage:
          'https://www.arweave.net/5B4togyXSpTf56pNNLE8YRVEhtpSY__SkE_2hkfbpMw?ext=webp',
        nftMint: 'FEq575Em29FNVmN73gbDQe7eVU4scSbrF4F6aCqoL2FC',
        nftName: 'LIFINITY Flares #5736',
        order: 11,
        safetyBoxPubkey: 'GV2jUSg6VNqSdP6GwK6MRyjSTtdSQSpUcMfRtJNZXSfi',
        store: '9tZSXEB9QZLbCqzpV12aBb1122KbcfggAD4JNFXFNKAX',
        vaultPubkey: 'Uzp4nRWuZozb36PbjepYJGM5Q44Bqiw1nYrDfQC1Hd1',
      },
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: '',
        nftDescription: '',
        nftImage: 'https://sld-babyapes.s3.amazonaws.com/2775.png',
        nftMint: '3MqVfztueWtTzUPJWK4N6XXRj3LzkEvnTzQRbQq6m28u',
        nftName: 'Baby Ape Social Club #2775',
        order: 10,
        safetyBoxPubkey: 'F5cdH3iszzYcfsBhFcp2Ri92DSg95JoZ3jg55s5tfrPS',
        store: '9MuebzBLetLFGRfiPEEnkRzTmS1B1xXs97ZywxJCb7xo',
        vaultPubkey: 'Uzp4nRWuZozb36PbjepYJGM5Q44Bqiw1nYrDfQC1Hd1',
      },
    ],
    state: 1,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    tokenTypeCount: 13,
    vaultPubkey: 'Uzp4nRWuZozb36PbjepYJGM5Q44Bqiw1nYrDfQC1Hd1',
  },
  {
    allowFurtherShareCreation: false,
    auction: {
      auction: {
        tickSize: new BN(1),
        auctionPubkey: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
        currentWinningBidPubkey: '11111111111111111111111111111111',
        endingAt: null,
        isEnabled: true,
        isStarted: false,
        startedAt: null,
        vaultPubKey: '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
      },
      bids: [],
    },
    authority: '9qZa1bRCRkMQfYqEE84VPX7Y1ohMXHudLTorbDFvcdpU',
    createdAt: 1640192700,
    fractionMint: 'ESrrTHaNKiC9saxaudX2j9iCM9r8qHRcLSrW5ypQ3W64',
    fractionTreasury: 'ByTL2emabe4DAdj1upGkBSGpfET66zhPj2GJyQKceQUu',
    fractionsSupply: new BN(1),
    hasMarket: true,
    isVerified: true,
    key: 3,
    lockedPricePerShare: new BN(1),
    priceMint: 'So11111111111111111111111111111111111111112',
    pricingLookupAddress: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
    realState: VaultState.Active,
    redeemTreasury: 'DjuDXD8VtcYMKq12ZnRuHpE3hx9iZWNtFaymSC6aEZRk',
    safetyBoxes: [
      {
        nftMint: '',
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'Blockasset Legends',
        nftDescription: 'Blockasset Verified Legends Collection by Dosbrak.',
        nftImage:
          'https://www.arweave.net/2Y3f2SeoT7HKHTQ_nUPfsLPyc59mPvNYSAsjKZuWNOk?ext=png',
        nftName: 'Blockasset Legends',
        order: 0,
        safetyBoxPubkey: 'BWpFYtGFhXPFXy5XNaXnCset1wSMS9ASfBMgMRwLDbk3',
        store: 'FojAEuq6X1inmYCpj3KJqWvn8uRt7yaZeCspevfrd5s6',
        vaultPubkey: '3oVLfsh7NdRKMEuX51whGgF594Pc4Tg2ZcWnMoAwZJum',
      },
    ],
    state: 1,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    tokenTypeCount: 1,
    vaultPubkey: '3oVLfsh7NdRKMEuX51whGgF594Pc4Tg2ZcWnMoAwZJum',
  },
  {
    allowFurtherShareCreation: false,
    auction: {
      auction: {
        tickSize: new BN(1),
        auctionPubkey: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
        currentWinningBidPubkey: '11111111111111111111111111111111',
        endingAt: null,
        isEnabled: true,
        isStarted: false,
        startedAt: null,
        vaultPubKey: '5yTUs6NXd9S9fsny9r5PHZvTtcXN3zLj7SDxLrn2z1Kr',
      },
      bids: [],
    },
    authority: 'AnUvEuvzDaueXZCaEMqWUsXa2aSmn2uR3bpqzWQE3XB5',
    createdAt: 1639411407,
    fractionMint: '6j28waP2NyoCBJrrVNHZuEzLDL25DXdNxMFsMNMxYht7',
    fractionTreasury: '4s1fyToXPjmwqqygFvkeLeZKgJxXR4Z5knWJeoUr8yxm',
    fractionsSupply: new BN(1),
    hasMarket: true,
    isVerified: true,
    key: 3,
    lockedPricePerShare: new BN(1),
    priceMint: 'So11111111111111111111111111111111111111112',
    pricingLookupAddress: '5neuPvTYSx1mczcCmf4R6hUj4fCuFEgpvstKnKwxYeUN',
    realState: VaultState.Active,
    redeemTreasury: '57pCxwKh8RoFSjuv5odePu47g4GgWvdzaGNAua94EvPE',
    safetyBoxes: [
      {
        isNftVerified: true,
        key: 1,
        nftAttributes: [],
        nftCollectionName: 'Solana Monkey Business',
        nftDescription:
          'SMB is a collection of 5000 randomly generated 24x24 pixels NFTs on the Solana Blockchain. Each SolanaMonkey is unique and comes with different type and attributes varying in rarity.',
        nftImage:
          'https://arweave.net/2OINffkTFvUwtPFfNKkNzQ7h8m-1UZsqQkr6bXKIH70',
        nftMint: '3De4WcBjfuZeCBqzun1PRUFh4UCgt4Cd9TqU8RCuerZt',
        nftName: 'SMB #3394',
        order: 0,
        safetyBoxPubkey: '2ehw4a2ypuHwohQ5R5uwu7HRNodssiPBbMPV6PDzBRUi',
        store: '4ZtSHgLxAR4gcK3W3Sz39esbLLwYzSapTa4xs93wh3Kt',
        vaultPubkey: 'FsGYFGm3mUpUaP4tLAjH3oxnQPT6GYAeWq7mZpZkTGh8',
      },
    ],
    state: 1,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    tokenTypeCount: 1,
    vaultPubkey: 'FsGYFGm3mUpUaP4tLAjH3oxnQPT6GYAeWq7mZpZkTGh8',
  },
];
